### ISSUE TITLE
Fundo de alguns diagramas

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-as#33]
Existem dois diagramas que têm um fundo que fazem com que sejam difíceis de os ler:
* [Diagrama de Sequencia - Registo](https://raw.githubusercontent.com/iptomar/projectary-as/9c46f0ad548adea353fe2de11f19ca6f3e6d696b/Diagramas%20de%20Sequ%C3%AAncia/Diagrama%20de%20Sequencia%20Registo.png)
* [Diagrama de Atividades - Candidatura](https://raw.githubusercontent.com/iptomar/projectary-as/154115e8f79842160b29ba2910e088d0a6b9cfd0/Diagramas%20de%20Atividades/Diagrama%20de%20atividades%20Candidatura.png)

@rafescu @rffantunes

**Comment by rffantunes** [comment]
Resolvido, já coloquei em branco.
